apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: is th
      targetPort: 3000
      nodePort: 30777
  type: NodePort
